id: IE17AD4A1
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-17T14:01:46+00:00'
last_modified: '2022-06-07T10:38:56.287911+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W1KG16609
  title: སངས་རྒྱས་བཅོམ་ལྡན་འདས་ཀྱི་སྐྱེས་རབས་བརྒྱ་པ།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    0FCE:
      image_group_id: I1KG16644
      title: Volume 1 of sangs rgyas bcos ldan 'das kyi skyes rabs brgya pa/
      total_pages: 752
      order: 1
      base_file: 0FCE.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
